# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("#title{font-size: 40px}\n"
"#usLineEdit, #pwdLineEdit, #loginBtn{font-size: 18px}\n"
"#usError, #pwdError {font-size: 10px; color: red}\n"
"#successMsg {font-size: 10px; color: green}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usLineEdit.setGeometry(QtCore.QRect(180, 120, 401, 71))
        self.usLineEdit.setObjectName("usLineEdit")
        self.pwdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwdLineEdit.setGeometry(QtCore.QRect(180, 260, 401, 71))
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(180, 390, 401, 61))
        self.loginBtn.setObjectName("loginBtn")
        self.successMsg = QtWidgets.QLabel(self.centralwidget)
        self.successMsg.setGeometry(QtCore.QRect(180, 460, 401, 31))
        self.successMsg.setText("")
        self.successMsg.setObjectName("successMsg")
        self.pwdError = QtWidgets.QLabel(self.centralwidget)
        self.pwdError.setGeometry(QtCore.QRect(180, 330, 401, 31))
        self.pwdError.setText("")
        self.pwdError.setObjectName("pwdError")
        self.usError = QtWidgets.QLabel(self.centralwidget)
        self.usError.setGeometry(QtCore.QRect(180, 190, 401, 31))
        self.usError.setText("")
        self.usError.setObjectName("usError")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(180, 30, 401, 31))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.loginBtn.clicked.connect(self.login)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usLineEdit.setPlaceholderText(_translate("MainWindow", "username..."))
        self.pwdLineEdit.setPlaceholderText(_translate("MainWindow", "password..."))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.title.setText(_translate("MainWindow", "LOGIN"))

    def login(self):
        self.successMsg.setText('')
        self.usError.setText('')
        self.pwdError.setText('')

        username = self.usLineEdit.text()
        password = self.pwdLineEdit.text()

        mydb = mc.connect(
            host = "localhost",
            user = "root",
            password = "",
            database = "application"
        )

        mycursor = mydb.cursor()
        mycursor.execute("SELECT * FROM users")
        result = mycursor.fetchall()
        for i in result:
            if username == i[0]:
                if password == i[1]:
                    self.successMsg.setText("Logged in!")
                else:
                    self.pwdError.setText("Password wrong!")
            else:
                self.usError.setText("Username wrong!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
